version: '3.3'

services:
    
    
    #service 1: definition of your spring-boot app 
    dellent:                        #it is just a name, which will be used only in this file.
      image: dellent-image               #name of the image after dockerfile executes
      container_name: dellent-application  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8080:8080"                       #docker containter port with your os port
      restart: always  
      